name: Build
on:
  push:
  workflow_dispatch:

env:
  BUILD_CONFIG: Release
  BUILD_DIR: build

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            generator: "Unix Makefiles"
          - name: macOS
            os: macos-latest
            generator: "Xcode"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Build and test"
        shell: bash
        env:
          GENERATOR: ${{ matrix.generator }}
        run: |
          ctest --build-and-test . ./build_$OSTYPE --build-generator $GENERATOR --test-command ctest --verbose
